//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Proje_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BahceMalzemeleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BahceMalzemeleri()
        {
            this.BahceMalzemeUruns = new HashSet<BahceMalzemeUrun>();
            this.Siparis = new HashSet<Sipari>();
        }
    
        public string BahceMalzemeAd { get; set; }
        public int MevcutAdet { get; set; }
        public short Fiyat { get; set; }
        public string Resim { get; set; }
        public Nullable<int> TedarikciID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BahceMalzemeUrun> BahceMalzemeUruns { get; set; }
        public virtual Tedarikci Tedarikci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sipari> Siparis { get; set; }
    }
}
