//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Proje_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitki
    {
        public int SeriNo { get; set; }
        public string Renk { get; set; }
        public Nullable<int> UretimNo { get; set; }
        public string BitkiCinsAd { get; set; }
    
        public virtual BitkiCin BitkiCin { get; set; }
        public virtual BitkiUretim BitkiUretim { get; set; }
    }
}
