//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Proje_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitkiUretim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BitkiUretim()
        {
            this.Bitkis = new HashSet<Bitki>();
            this.BitkiUretim_HamMadde = new HashSet<BitkiUretim_HamMadde>();
        }
    
        public int UretimNo { get; set; }
        public short SeraNo { get; set; }
        public int UretimAded { get; set; }
        public string BitkiCinsAd { get; set; }
        public System.DateTime Tarih { get; set; }
        public string Renk { get; set; }
        public Nullable<int> Kayıt_Eden_Calisan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bitki> Bitkis { get; set; }
        public virtual BitkiCin BitkiCin { get; set; }
        public virtual Calisan Calisan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitkiUretim_HamMadde> BitkiUretim_HamMadde { get; set; }
    }
}
