//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Proje_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitkiUretim_HamMadde
    {
        public int KullanımNo { get; set; }
        public int UretimNo { get; set; }
        public string HamMaddeAd { get; set; }
        public string MiktarCinsi { get; set; }
        public int Miktar { get; set; }
    
        public virtual BitkiUretim BitkiUretim { get; set; }
        public virtual HamMadde HamMadde { get; set; }
        public virtual MiktarCin MiktarCin { get; set; }
    }
}
