//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Proje_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitkiCin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BitkiCin()
        {
            this.Bitkis = new HashSet<Bitki>();
            this.BitkiUretims = new HashSet<BitkiUretim>();
            this.Siparis = new HashSet<Sipari>();
        }
    
        public string BitkiCinsAd { get; set; }
        public int MevcutAded { get; set; }
        public string LatinceAd { get; set; }
        public string BitkiTur { get; set; }
        public short Fiyat { get; set; }
        public string Resim { get; set; }
        public Nullable<short> DepoID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bitki> Bitkis { get; set; }
        public virtual BitkiTur BitkiTur1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitkiUretim> BitkiUretims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sipari> Siparis { get; set; }
    }
}
