//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Proje_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HamMadde
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HamMadde()
        {
            this.BitkiUretim_HamMadde = new HashSet<BitkiUretim_HamMadde>();
            this.HamMadde_SatinAlma = new HashSet<HamMadde_SatinAlma>();
        }
    
        public string HamMaddeAd { get; set; }
        public int MevcutMiktar { get; set; }
        public string MiktarCins { get; set; }
        public short DepoID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitkiUretim_HamMadde> BitkiUretim_HamMadde { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HamMadde_SatinAlma> HamMadde_SatinAlma { get; set; }
        public virtual MiktarCin MiktarCin { get; set; }
    }
}
