//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Proje_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HamMadde_SatinAlma
    {
        public int SatinAlmaNumarasi { get; set; }
        public string HamMaddeAd { get; set; }
        public int TedarikciID { get; set; }
        public string MiktarCins { get; set; }
        public int Miktar { get; set; }
        public int Tutar { get; set; }
        public int SatinAlanCalisan { get; set; }
    
        public virtual Calisan Calisan { get; set; }
        public virtual HamMadde HamMadde { get; set; }
        public virtual MiktarCin MiktarCin { get; set; }
        public virtual Tedarikci Tedarikci { get; set; }
    }
}
