//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Proje_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int SepetID { get; set; }
        public int SiparisID { get; set; }
        public int MusteriID { get; set; }
        public string Urun { get; set; }
        public Nullable<short> UrunAdet { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Sipari Sipari { get; set; }
    }
}
