//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Proje_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sipari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sipari()
        {
            this.Sepets = new HashSet<Sepet>();
        }
    
        public int SiparisID { get; set; }
        public int MusteriID { get; set; }
        public Nullable<System.DateTime> SiparisTarihi { get; set; }
        public string Adres { get; set; }
        public string BitkiCinsAd { get; set; }
        public Nullable<short> SiparisAdedi { get; set; }
        public string YanMalzeme { get; set; }
        public string Renk { get; set; }
    
        public virtual BahceMalzemeleri BahceMalzemeleri { get; set; }
        public virtual BitkiCin BitkiCin { get; set; }
        public virtual Musteri Musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepets { get; set; }
    }
}
