//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Proje_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tedarikci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tedarikci()
        {
            this.BahceMalzemeleris = new HashSet<BahceMalzemeleri>();
            this.HamMadde_SatinAlma = new HashSet<HamMadde_SatinAlma>();
        }
    
        public int TedarikciID { get; set; }
        public string FirmaAd { get; set; }
        public string Adres { get; set; }
        public Nullable<int> Telefon { get; set; }
        public string Email { get; set; }
        public string IBAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BahceMalzemeleri> BahceMalzemeleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HamMadde_SatinAlma> HamMadde_SatinAlma { get; set; }
    }
}
